# Generated by Django 4.2.1 on 2023-06-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0002_alter_chatroom_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='recipient',
            field=models.TextField(),
        ),
    ]
