# Generated by Django 4.2.2 on 2023-06-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0009_remove_report_announcement_delete_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='static/socialnetworkapp/profile.png', null=True, upload_to='images/'),
        ),
    ]
