# Generated by Django 4.2.2 on 2023-06-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworkapp', '0010_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='C:/Users/Deep_/Desktop/DjangoSocialNetwork/profile.png', null=True, upload_to='images/'),
        ),
    ]
